export const donorData = {
  name: "Ahmed Hassan",
  bloodType: "O+",
  phone: "+880 1712-999888",
  email: "ahmed.hassan@email.com",
  address: "House 123, Road 15, Dhanmondi, Dhaka-1205",
  totalDonations: 15,
  livesImpacted: 45,
  lastDonation: "2024-02-15",
  nextEligible: "2024-05-15",
  memberSince: "2020",
  rating: 4.9,
  responseRate: "98%",
  isVerified: true,
}
export 
const incomingRequests = [
  {
    id: "REQ-001",
    patient: "Rashid Ali",
    bloodType: "O+",
    unitsNeeded: 2,
    hospital: "Dhaka Medical College",
    urgency: "Critical",
    distance: "3.2 km",
    requestTime: "30 min ago",
    requesterPhone: "+880 1712-345678",
    condition: "Emergency Surgery",
  },
  {
    id: "REQ-002",
    patient: "Nasir Ahmed",
    bloodType: "O+",
    unitsNeeded: 1,
    hospital: "Square Hospital",
    urgency: "Urgent",
    distance: "5.8 km",
    requestTime: "2 hours ago",
    requesterPhone: "+880 1987-654321",
    condition: "Accident Victim",
  },
]
export const donationHistory = [
  {
    id: "DON-001",
    date: "2024-02-15",
    hospital: "Dhaka Medical College",
    recipient: "Ahmed Hassan",
    units: 1,
    status: "Completed",
    feedback: "Excellent donor, very cooperative",
    urgency: "Critical",
  },
  {
    id: "DON-002",
    date: "2024-01-10",
    hospital: "Square Hospital",
    recipient: "Fatima Begum",
    units: 2,
    status: "Completed",
    feedback: "Thank you for saving my life",
    urgency: "Urgent",
  },
]
