export const userRequestHistory = [
  {
    id: "REQ-U001",
    bloodType: "O+",
    unitsNeeded: 2,
    hospital: "Dhaka Medical College",
    requestDate: "2024-03-10",
    status: "Completed",
    urgency: "Critical",
    donorMatched: "Rahman Ali",
    completedDate: "2024-03-11",
  },
  {
    id: "REQ-U002",
    bloodType: "O+",
    unitsNeeded: 1,
    hospital: "Square Hospital",
    requestDate: "2024-02-15",
    status: "Completed",
    urgency: "Normal",
    donorMatched: "Karim Uddin",
    completedDate: "2024-02-16",
  },
]

export const availableDonors = [
  {
    name: "Rahman Ali",
    bloodType: "O+",
    location: "Dhanmondi, Dhaka",
    distance: "2.5 km",
    rating: 4.9,
    totalDonations: 15,
    lastDonation: "2 weeks ago",
    availability: "Available",
    phone: "+880 1712-345678",
    preferredTime: "Morning",
    isVerified: true,
  },
  {
    name: "Karim Uddin",
    bloodType: "O+",
    location: "Uttara, Dhaka",
    distance: "5.2 km",
    rating: 4.8,
    totalDonations: 12,
    lastDonation: "1 month ago",
    availability: "Available",
    phone: "+880 1555-123456",
    preferredTime: "Evening",
    isVerified: true,
  },
]
export const userData = {
  name: "Ahmed Hassan",
  bloodType: "O+",
  phone: "+880 1712-999888",
  email: "ahmed.hassan@email.com",
  address: "House 123, Road 15, Dhanmondi, Dhaka-1205",
  memberSince: "2023",
  totalRequests: 3,
  livesImpacted: 6,
  rating: 4.9,
  isVerified: true,
}
