// Mock data for admin dashboard
export const systemStats = {
  totalUsers: 2847,
  totalDonors: 1523,
  activeRequests: 47,
  completedRequests: 892,
  totalDonations: 1205,
  livesImpacted: 3615,
  responseRate: "94%",
  systemUptime: "99.9%",
};

export const recentUsers = [
  {
    id: "USR-001",
    name: "Ahmed Hassan",
    email: "ahmed@email.com",
    bloodType: "O+",
    joinDate: "2024-03-15",
    status: "Active",
    verified: true,
    requests: 3,
  },
  {
    id: "USR-002",
    name: "Fatima Begum",
    email: "fatima@email.com",
    bloodType: "A+",
    joinDate: "2024-03-14",
    status: "Active",
    verified: false,
    requests: 1,
  },
  {
    id: "USR-003",
    name: "Rahman Ali",
    email: "rahman@email.com",
    bloodType: "B+",
    joinDate: "2024-03-13",
    status: "Inactive",
    verified: true,
    requests: 0,
  },
];

export const recentDonors = [
  {
    id: "DON-001",
    name: "Karim Uddin",
    email: "karim@email.com",
    bloodType: "O+",
    joinDate: "2020-01-15",
    status: "Active",
    verified: true,
    donations: 25,
    rating: 4.9,
    lastDonation: "2024-02-20",
  },
  {
    id: "DON-002",
    name: "Nasir Ahmed",
    email: "nasir@email.com",
    bloodType: "A-",
    joinDate: "2021-06-10",
    status: "Active",
    verified: true,
    donations: 18,
    rating: 4.8,
    lastDonation: "2024-03-01",
  },
  {
    id: "DON-003",
    name: "Rashid Ali",
    email: "rashid@email.com",
    bloodType: "B-",
    joinDate: "2022-03-20",
    status: "Inactive",
    verified: false,
    donations: 5,
    rating: 4.5,
    lastDonation: "2023-12-15",
  },
];

export const recentRequests = [
  {
    id: "REQ-001",
    patient: "Ahmed Hassan",
    requester: "Fatima Hassan",
    bloodType: "O+",
    unitsNeeded: 2,
    hospital: "Dhaka Medical College",
    urgency: "Critical",
    status: "Pending",
    requestDate: "2024-03-15",
    assignedDonor: null,
  },
  {
    id: "REQ-002",
    patient: "Nasir Ahmed",
    requester: "Rashida Ahmed",
    bloodType: "A+",
    unitsNeeded: 1,
    hospital: "Square Hospital",
    urgency: "Urgent",
    status: "Assigned",
    requestDate: "2024-03-14",
    assignedDonor: "Karim Uddin",
  },
  {
    id: "REQ-003",
    patient: "Rahman Ali",
    requester: "Salma Ali",
    bloodType: "B+",
    unitsNeeded: 3,
    hospital: "Apollo Hospital",
    urgency: "Normal",
    status: "Completed",
    requestDate: "2024-03-13",
    assignedDonor: "Nasir Ahmed",
  },
];

export const systemAlerts = [
  {
    id: "ALT-001",
    type: "Critical",
    message: "Low O- blood type donors in Dhaka area",
    time: "30 min ago",
    resolved: false,
  },
  {
    id: "ALT-002",
    type: "Warning",
    message: "Server response time increased by 15%",
    time: "2 hours ago",
    resolved: false,
  },
  {
    id: "ALT-003",
    type: "Info",
    message: "Monthly backup completed successfully",
    time: "1 day ago",
    resolved: true,
  },
];
